name: road
channels:
  - conda-forge
  - pytorch
  - pyg
  - defaults
dependencies:
  - python=3.9
  - osmnx
  - geopandas
  - pytorch::pytorch=1.11.0
  - cudatoolkit=11.3
  - cudnn
  - pyg::pyg
  - numpy
  - shapely
  - swifter
  - joblib
  - gensim
  - pip:
      - mxnet-cu112
      - pytorch-lightning
  #     - pdoc3
  #     - matplotlib
  #     - scipy
  #     - pandas
  #     - plotly
  #- networkx
  #- folium
  #- overpass
