name: road-emb
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pytorch
  - numpy
  - pytest
  - black
  - pip
  - pip:
      - pdoc3
      - matplotlib
      - scipy
      - pandas
      - plotly
      - networkx
