name: road
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.9
  - osmnx
  - geopandas
  - pytorch::pytorch=1.11.0
  - pytorch::cudatoolkit=11.3
  - numpy
  - shapely
  - swifter
  - joblib
  - gensim
  # - pip:
  #     - pdoc3
  #     - matplotlib
  #     - scipy
  #     - pandas
  #     - plotly
  #- networkx
  #- folium
  #- overpass
