name: road-emb
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.9
  - osmnx
  - pytorch
  - numpy
  - shapely
  - swifter
  # - pip:
  #     - pdoc3
  #     - matplotlib
  #     - scipy
  #     - pandas
  #     - plotly
  #- networkx
  #- folium
  #- overpass
