name: road
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.9
  - osmnx
  - geopandas
  - pytorch=1.10.1
  - cudatoolkit=11.3
  - numpy
  - shapely
  - swifter
  # - pip:
  #     - pdoc3
  #     - matplotlib
  #     - scipy
  #     - pandas
  #     - plotly
  #- networkx
  #- folium
  #- overpass
